* статические библиотеки (и библиотеки вообще)

** что такое статическая библиотека?
Статическая библиотека это архив, состоящий из объектников.

** для чего нужны статические библиотеки?
Библиотеки нужны для переиспользования кода

*** Существует понятие стандартной библиотеки
- в свифте есть [[https://developer.apple.com/documentation/swift/swift_standard_library][стандартная библиотека]] которая содержит в себе print, базовые типы...
- в си есть комплекс стандартных библиотека (stdlib, stdio...)
- в паскале тоже есть стандартная библиотека
- а также во многих других языках

*** Как реализованы стандартные библиотеки
- свифтовые библиотеки лежат в '/Library/Developer/Toolchains/swift-latest.xctoolchain/usr/lib/swift/macosx'
- сишные библиотеки лежат в '/usr/lib'
- паскальная библиотека вшита в компилятор

#+BEGIN_QUOTE
отличие между .dylib и .a можно посмотреть [[https://stackoverflow.com/questions/40841670/what-is-the-difference-between-dylib-and-a-lib-in-ios][здесь]]
#+END_QUOTE

*** подход паскаля vs подход библиотек
- минус подхода паскаля в том, что на изменение в стандартной библиотеке нужно выпускать новую версию компилятора
- прелесть подхода с библиотекой в том, что тебе просто нужно обновить библиотеки, не трогая компилятор

*** библиотеки vs объектники
Все то же самое можно было бы реализовать использую только объектники. Зачем же нам статические и динамические библиотеки?

Стоит отметить, что "минимальная единица" линковки это объектник. То есть линкер может соединять только объектники.

Получается, что если бы сишная stdlib была просто stdlib.o, то после линковки с этой библиотекой результат будет иметь в себе весь код этого объектника, даже если использует только часть методов.

При линковке с библиотекой, которая архив объектников, линкер слинкует лишь те объектники, код из которых используется.

** утилита ar
*** создание статиечкой библиотеки
ar -rcs lib<NAME>.a *.o

Для простоты можно представить что он просто соединяет все объект файлы в один

*** инспекция статической библиотеки
ar -t <STATIC_LIB> список объектников
ar -x <STATIC_LIB> экстракция объектников

*** линковка со статической библиотекой

